spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_EMAIL_USERNAME}
    password: ${SMTP_EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: notification-service-test
      client-id: consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      fetch-max-wait-ms: 500
      fetch-min-bytes: 16384
      enable-auto-commit: false
      heartbeat-interval-ms: 3000
      session-timeout-ms: 45000
      auto-offset-reset: ${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
      properties:
        bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: "order.created:com.notifications.notification_service.domain.event.OrderCreatedEvent"
        spring.json.use.type.headers: false